sparkfun/SparkFun-Eagle-Libraries

- SparkFun-Capacitors.lbr
also removed the 0402 version of this cap
> Added new Wurth Electronik 0.1uF 50V 0603 cap

- SparkFun-IC-Logic.lbr
Due to supply chain issues, we needed to find an alt.
> Added a second option for single buffer IC

- SparkFun-IC-Amplifiers.lbr
- SparkFun-IC-Logic.lbr
> Added Prefix U to 2 parts.

- SparkFun-Sensors.lbr
> Adds new AMS TMF882x dToF Sensor

- SparkFun-Resistors.lbr
Added existing 5% 0603 resistor.
> Added existing resistor to lib.

- SparkFun-IC-Power.lbr
XC6222B331MR-G 3.3V 700mA SOT-25 LDO.
> Add xc6222 vreg

- SparkFun-Connectors.lbr
Needed to move rectangle on tKeepout to tRestrict per the drawing. Supposed to prevent traces not other components.
> FF uSD added tRestrict.

- SparkFun-Hardware.lbr
> Re-add M2.5_1.5MM_TALL STAND-OFF-REFLOW-M2.5

- SparkFun-Boards.lbr
Add logical device for ThingPlus.
Rename ThingPlus to add _PHYSICAL for differentiation.
> Add ThingPlus Logical Board.

- SparkFun-MicroMod.lbr
Allows for function boards to access processor board boot and reset lines.
> Added MCU control pins.

- SparkFun-IC-Power.lbr
Short pins
Remove pad numbers from schematic pins
> Update MAX1704X with latest standards

- SparkFun-GPS.lbr
* Removes "RSVD" pin
* Updates SPI lines to new nomenclature
* Fixes device name to have a dash rather than an underscore before the model part number
> Updates symbol name/value to vector

- SparkFun-Coils.lbr
- SparkFun-IC-Power.lbr
- SparkFun-Resistors.lbr
93.1k 0402
41.2k 0402
6.8uH smd inductor
AP63357 adjustable vreg
> Add passives, vreg.

- SparkFun-IC-Power.lbr
It was updated in the local lib but those changes were never carried over. Paste is too much.
> Update AP63357 footprint

- SparkFun-RF.lbr
> Changes proportional text to vector, updates notes on physical dimension

- SparkFun-IC-Special-Function.lbr
As used on RTK Facet and L-Band
> Add USB2514B four port USB hub

- SparkFun-Jumpers.lbr
- SparkFun-RF.lbr
Reduce the paste on the BP2G1+ RF pads by 80%
Make the SOIC jumpers rounded
Reduce the gap to ~6 mil
> Update SOIC Pad jumpers

- SparkFun-Sensors.lbr
Added device, footprint, and schematic to the repo
> Added TMAG5273 to repo

- SparkFun-Connectors.lbr
-as used on some of the myoware boards.
> Adds 1.0mm pitched JST-SH 2-pin SMD connector

- SparkFun-Connectors.lbr
Adds CONN-20948 that @nseidle suggested. Could you please give this a quick look and merge if all seems good? I just copied the dimensions and such from the KiCad part. Thanks!
> Add Micro SD Atom connector
